#!/usr/bin/env python3
"""Check a fresh compact clone and optionally write ignored local configuration."""
from __future__ import annotations

import argparse
import json
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def command_version(command: list[str]) -> str | None:
    try:
        result = subprocess.run(command, capture_output=True, text=True, timeout=30, check=False)
    except (OSError, subprocess.TimeoutExpired):
        return None
    if result.returncode:
        return None
    return (result.stdout or result.stderr).splitlines()[0].strip()


def discover_blender() -> Path | None:
    configured = os.environ.get("BLENDER_BIN")
    candidates = [
        Path(configured) if configured else None,
        Path(shutil.which("blender")) if shutil.which("blender") else None,
        Path("/Applications/Blender.app/Contents/MacOS/Blender"),
        Path("C:/Program Files/Blender Foundation/Blender 5.1/blender.exe"),
        Path("C:/Program Files/Blender Foundation/Blender 5.0/blender.exe"),
    ]
    return next((path.resolve() for path in candidates if path and path.is_file()), None)


def script_ok(relative: str) -> bool:
    result = subprocess.run(
        [sys.executable, str(ROOT / relative)], capture_output=True, text=True, check=False, timeout=120
    )
    return result.returncode == 0


def write_local_config(user: str, asset_vault: str) -> list[str]:
    env_path = ROOT / "app" / ".env"
    env_path.write_text(
        "# Generated by tools/bootstrap.py --configure; never commit this file.\n"
        f"BLENDER_ROOT_HOST={ROOT}\n"
        f"BLENDER_ASSET_VAULT={asset_vault}\n"
        f"STUDIO_USER={user}\n"
        "DEFAULT_BLEND_RELATIVE=\n",
        encoding="utf-8",
    )
    local_path = ROOT / ".studio.local.json"
    local_path.write_text(
        json.dumps(
            {
                "schema_version": 1,
                "root": str(ROOT),
                "blender_bin": str(discover_blender() or ""),
                "asset_vault": asset_vault,
                "studio_user": user,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    return [str(env_path.relative_to(ROOT)), str(local_path.relative_to(ROOT))]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--configure", action="store_true", help="Écrire app/.env et .studio.local.json")
    parser.add_argument("--user", default=os.environ.get("STUDIO_USER") or os.environ.get("USER") or "local-user")
    parser.add_argument("--asset-vault", default=os.environ.get("BLENDER_ASSET_VAULT", ""))
    args = parser.parse_args()

    blender = discover_blender()
    vault = Path(args.asset_vault).expanduser().resolve() if args.asset_vault else None
    checks = {
        "python_supported": sys.version_info >= (3, 11),
        "git": command_version(["git", "--version"]),
        "catalog": script_ok("tools/verify_asset_catalog.py"),
        "distribution_budget": script_ok("tools/check_distribution_budget.py"),
        "blender": command_version([str(blender), "--version"]) if blender else None,
        "ffmpeg_optional": command_version(["ffmpeg", "-version"]),
        "ffprobe_optional": command_version(["ffprobe", "-version"]),
        "docker_optional": command_version(["docker", "--version"]),
        "docker_compose_optional": command_version(["docker", "compose", "version"]),
        "asset_vault_optional": bool(vault and vault.is_dir()),
    }
    core_keys = ("python_supported", "git", "catalog", "distribution_budget")
    core_ready = all(bool(checks[key]) for key in core_keys)
    written = write_local_config(args.user, str(vault or "")) if args.configure else []
    report = {
        "schema_version": 2,
        "root": str(ROOT),
        "platform": platform.platform(),
        "ready_core": core_ready,
        "ready_for_blender_batch": core_ready and bool(checks["blender"]),
        "ready_for_animation_media": core_ready and bool(checks["blender"] and checks["ffmpeg_optional"] and checks["ffprobe_optional"]),
        "checks": checks,
        "configured_files": written,
        "notes": {
            "git_lfs": "not required and forbidden for this compact distribution",
            "submodules": "not required and forbidden for this compact distribution",
            "asset_vault": "optional; catalog browsing and new creation work without it",
        },
        "next": "run workflows/tools/studio_readiness_check.py",
    }
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report["ready_for_blender_batch"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
